version: "3.9"

services:
  api:
    image: image_name
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    networks:
      - my-net
    env_file:
      - .env
    command: []

networks:
  my-net:
    driver: bridge
